// File: commands/group/link.js (Format: JavaScript)

/**
 * Mengambil link undangan grup
 */
module.exports = {
    name: 'linkgroup',
    aliases: ['linkgc', 'link'],
    category: 'group',
    description: 'Mendapatkan link undangan grup ini',
    groupOnly: true,
    admin: true,
    botAdmin: true,
    execute: async (wann, msg, args, { groupMetadata }) => {
        const remoteJid = msg.key.remoteJid;

        try {
            const code = await wann.groupInviteCode(remoteJid);
            const response = `*Link Group:* ${groupMetadata.subject || 'Grup'}\n\nhttps://chat.whatsapp.com/${code}\n\n_Generated by Wann Assistant_`;
            
            await wann.sendMessage(remoteJid, { text: response }, { quoted: msg });
        } catch (e) {
            await wann.sendMessage(remoteJid, { text: '❌ Gagal mengambil link grup. Pastikan bot adalah Admin.' }, { quoted: msg });
        }
    }
};