/**
 * TULIPNEX MARKET EVENTS DATABASE
 * Path: ./lib/trading-events.js
 * Total: 200 Events (20 Global + 30 IVL + 30 LBT + 30 IRC + 30 LTN + 30 RSX + 30 TNX)
 * Description: Arsitektur Ekonomi Kompleks (Bullish & Bearish Scenarios)
 * Update: Menambahkan 100 event isu sesaat, rumor, dan tren pasar tanpa mematikan aset.
 */

const eventPool = [
    // =========================================================================
    // 🌍 TIER 0: GLOBAL EVENTS (20 Events) - Memengaruhi Seluruh Market
    // =========================================================================
    { title: 'GLOBAL RECESSION', msg: 'Krisis ekonomi dunia! Seluruh harga aset botani anjlok parah.', type: 'bear', ticker: 'GLOBAL', mult: -3.5, dur: 8 },
    { title: 'ECONOMIC BOOM', msg: 'Era keemasan tiba! Investor mengalirkan dana ke semua sektor.', type: 'bull', ticker: 'GLOBAL', mult: 2.5, dur: 10 },
    { title: 'MARKET MANIA', msg: 'Spekulasi berlebihan! Volatilitas seluruh pasar meningkat tajam.', type: 'bull', ticker: 'GLOBAL', mult: 4.0, dur: 5 },
    { title: 'BLACK MONDAY', msg: 'Panic selling massal di seluruh bursa TulipNex!', type: 'bear', ticker: 'GLOBAL', mult: -5.0, dur: 3 },
    { title: 'TECH REVOLUTION', msg: 'Infrastruktur Nexus baru diluncurkan. Semua aset menguat!', type: 'bull', ticker: 'GLOBAL', mult: 2.0, dur: 12 },
    { title: 'FED RATE CUT', msg: 'Suku bunga dipotong, uang murah mengalir deras ke aset berisiko!', type: 'bull', ticker: 'GLOBAL', mult: 2.8, dur: 7 },
    { title: 'WAR ESCALATION', msg: 'Ketegangan geopolitik memanas, investor kabur ke Safe Haven!', type: 'bear', ticker: 'GLOBAL', mult: -3.8, dur: 6 },
    { title: 'ALIEN TECH REVEAL', msg: 'Teknologi ekstraterestrial dipublikasikan, memicu euforia massal.', type: 'bull', ticker: 'GLOBAL', mult: 3.2, dur: 9 },
    { title: 'SOLAR FLARE', msg: 'Badai matahari merusak satelit komunikasi finansial global.', type: 'bear', ticker: 'GLOBAL', mult: -4.5, dur: 4 },
    { title: 'HOLIDAY RALLY', msg: 'Euforia akhir tahun mendorong daya beli pasar secara gila-gilaan.', type: 'bull', ticker: 'GLOBAL', mult: 2.2, dur: 11 },
    { title: 'INFLATION SCARE', msg: 'Data inflasi mendadak naik! Investor ketakutan dan menarik aset.', type: 'bear', ticker: 'GLOBAL', mult: -2.5, dur: 5 },
    { title: 'GREEN ENERGY PUSH', msg: 'Pakta energi ramah lingkungan global mendongkrak minat ke aset tech-botani.', type: 'bull', ticker: 'GLOBAL', mult: 2.0, dur: 8 },
    { title: 'VIRAL TIKTOK TREND', msg: 'Tren investasi massal dari influencer global menaikkan volume sesaat.', type: 'bull', ticker: 'GLOBAL', mult: 3.0, dur: 4 },
    { title: 'EXCHANGE GLITCH', msg: 'Glitch visual di bursa utama memicu kepanikan dan aksi jual sesaat.', type: 'bear', ticker: 'GLOBAL', mult: -3.0, dur: 3 },
    { title: 'PEACE TREATY RUMOR', msg: 'Rumor gencatan senjata konflik global memicu optimisme semu di pasar.', type: 'bull', ticker: 'GLOBAL', mult: 1.8, dur: 6 },
    { title: 'SUPPLY CHAIN DELAY', msg: 'Keterlambatan pengiriman chip global menekan harga seluruh aset digital.', type: 'bear', ticker: 'GLOBAL', mult: -2.2, dur: 7 },
    { title: 'INSTITUTIONAL FOMO', msg: 'Fear of Missing Out dari institusi mendongkrak harga secara tiba-tiba!', type: 'bull', ticker: 'GLOBAL', mult: 3.5, dur: 5 },
    { title: 'DATA LEAK HOAX', msg: 'Hoax kebocoran data raksasa membuat pasar terkoreksi tajam sementara.', type: 'bear', ticker: 'GLOBAL', mult: -3.2, dur: 4 },
    { title: 'TECH SUBSIDY', msg: 'Pengumuman subsidi infrastruktur teknologi memicu sentimen positif.', type: 'bull', ticker: 'GLOBAL', mult: 1.9, dur: 7 },
    { title: 'SOLAR STORM WARNING', msg: 'Peringatan potensi badai matahari membuat investor ragu berinvestasi.', type: 'bear', ticker: 'GLOBAL', mult: -2.0, dur: 5 },

    // =========================================================================
    // 🌱 TIER 1: IVYLINK (IVL) - 30 Events
    // =========================================================================
    { title: 'ADOPSI MASSAL', msg: 'IvyLink resmi digunakan sebagai standar IoT kebun pintar!', type: 'bull', ticker: 'IVL', mult: 1.5, dur: 5 },
    { title: 'GANGGUAN NODES', msg: 'Jaringan IvyLink mengalami gangguan koneksi di pedesaan.', type: 'bear', ticker: 'IVL', mult: -1.8, dur: 3 },
    { title: 'SUBSIDI BOTANI', msg: 'Pemerintah memberikan subsidi bagi pengguna IvyLink baru.', type: 'bull', ticker: 'IVL', mult: 1.3, dur: 10 },
    { title: 'SERANGAN HAMA', msg: 'Hama digital terdeteksi pada sistem sensor IvyLink.', type: 'bear', ticker: 'IVL', mult: -2.0, dur: 4 },
    { title: 'UPDATE FIRMWARE', msg: 'Update firmware terbaru membuat IvyLink 2x lebih efisien!', type: 'bull', ticker: 'IVL', mult: 1.4, dur: 6 },
    { title: 'SMART FARM COLAB', msg: 'Kontrak besar ditandatangani dengan 1000 kebun vertikal kota.', type: 'bull', ticker: 'IVL', mult: 1.6, dur: 6 },
    { title: 'SENSOR MALFUNCTION', msg: 'Bug membuat ribuan sensor IvyLink memberikan data cuaca palsu.', type: 'bear', ticker: 'IVL', mult: -1.7, dur: 4 },
    { title: 'GREEN SUBSIDY', msg: 'Keringanan pajak energi hijau meningkatkan margin profit IVL.', type: 'bull', ticker: 'IVL', mult: 1.4, dur: 8 },
    { title: 'RIVAL IOT LAUNCH', msg: 'Pesaing meluncurkan sensor yang lebih murah dari IvyLink.', type: 'bear', ticker: 'IVL', mult: -1.5, dur: 5 },
    { title: 'BATTERY BREAKTHROUGH', msg: 'Pembaruan baterai membuat sensor IvyLink bertahan 10 tahun.', type: 'bull', ticker: 'IVL', mult: 1.7, dur: 7 },
    { title: 'SUPPLY CHAIN ISSUE', msg: 'Pabrik chip IvyLink terbakar, pasokan global terhambat drastis.', type: 'bear', ticker: 'IVL', mult: -2.1, dur: 5 },
    { title: 'SCHOOL INTEGRATION', msg: 'Sekolah-sekolah mulai menggunakan IVL untuk lab biologi mereka.', type: 'bull', ticker: 'IVL', mult: 1.3, dur: 9 },
    { title: 'PRIVACY LAWSUIT', msg: 'Gugatan privasi data menargetkan enkripsi milik IvyLink.', type: 'bear', ticker: 'IVL', mult: -1.9, dur: 4 },
    { title: 'ECO-AWARD WINNER', msg: 'IvyLink memenangkan penghargaan teknologi ramah lingkungan tahun ini.', type: 'bull', ticker: 'IVL', mult: 1.5, dur: 6 },
    { title: 'OBSOLESCENCE RUMOR', msg: 'Beredar rumor IvyLink akan segera ditinggalkan oleh pengembangnya.', type: 'bear', ticker: 'IVL', mult: -2.2, dur: 3 },
    { title: 'WEATHER API BUG', msg: 'Bug pada API cuaca membuat prediksi panen IVL meleset dan merugikan petani.', type: 'bear', ticker: 'IVL', mult: -1.6, dur: 5 },
    { title: 'DRONE DELIVERY', msg: 'Uji coba pengiriman bibit terintegrasi drone IVL dikabarkan sukses besar!', type: 'bull', ticker: 'IVL', mult: 1.8, dur: 6 },
    { title: 'FERTILIZER SHORTAGE', msg: 'Kelangkaan pupuk dunia menekan sentimen utilitas sensor IVL.', type: 'bear', ticker: 'IVL', mult: -1.5, dur: 7 },
    { title: 'NEW SOIL SENSOR', msg: 'Sensor kelembaban tanah generasi baru diluncurkan oleh IvyLink.', type: 'bull', ticker: 'IVL', mult: 1.4, dur: 8 },
    { title: 'RUST FUNGUS RUMOR', msg: 'Isu wabah jamur karat pada ekosistem IvyLink membuat pasar was-was.', type: 'bear', ticker: 'IVL', mult: -1.9, dur: 4 },
    { title: 'AGRI-TECH EXPO', msg: 'IVL memenangkan nominasi stan teknologi terbaik di pameran agrikultur.', type: 'bull', ticker: 'IVL', mult: 1.3, dur: 5 },
    { title: 'ROUTER OVERHEAT', msg: 'Cuaca panas ekstrem membuat sebagian besar router IVL pedesaan offline sementara.', type: 'bear', ticker: 'IVL', mult: -2.0, dur: 3 },
    { title: 'WATER SAVING TECH', msg: 'IvyLink merilis algoritma update yang mampu menghemat air irigasi hingga 30%.', type: 'bull', ticker: 'IVL', mult: 1.6, dur: 7 },
    { title: 'PESTICIDE BAN', msg: 'Pelarangan pestisida oleh pemerintah membuat petani IVL harus mengatur ulang sensor.', type: 'bear', ticker: 'IVL', mult: -1.4, dur: 6 },
    { title: 'COMMUNITY HARVEST', msg: 'Panen raya komunitas pengguna IVL secara global dilaporkan melebihi ekspektasi!', type: 'bull', ticker: 'IVL', mult: 1.7, dur: 5 },
    { title: 'FAKE SEED SCAM', msg: 'Penipuan bibit palsu mengatasnamakan kemitraan IvyLink merusak citra merek.', type: 'bear', ticker: 'IVL', mult: -1.8, dur: 4 },
    { title: 'AGRO-INFLUENCER', msg: 'Influencer pertanian populer memuji efektivitas IVL dalam vlog terbarunya.', type: 'bull', ticker: 'IVL', mult: 1.5, dur: 4 },
    { title: 'BLUETOOTH INTERFERENCE', msg: 'Sinyal radio militer lokal tanpa sengaja mengganggu konektivitas node IVL.', type: 'bear', ticker: 'IVL', mult: -1.5, dur: 5 },
    { title: 'AI CROP PREDICTION', msg: 'Fitur AI baru IVL sangat akurat memprediksi hasil panen masa depan.', type: 'bull', ticker: 'IVL', mult: 1.6, dur: 8 },
    { title: 'BIRD MIGRATION', msg: 'Migrasi burung musiman parah merusak beberapa patok sensor eksternal IVL.', type: 'bear', ticker: 'IVL', mult: -1.3, dur: 6 },

    // =========================================================================
    // 🌼 TIER 2: LILYBIT (LBT) - 30 Events
    // =========================================================================
    { title: 'SECURITY UPGRADE', msg: 'Dompet LilyBit kini memiliki enkripsi tingkat militer!', type: 'bull', ticker: 'LBT', mult: 1.7, dur: 5 },
    { title: 'OVERLOAD SERVER', msg: 'Server LilyBit kewalahan menangani transaksi baru.', type: 'bear', ticker: 'LBT', mult: -1.5, dur: 4 },
    { title: 'VIRAL TREND', msg: 'Tantangan menanam bunga dengan LilyBit viral di media sosial!', type: 'bull', ticker: 'LBT', mult: 2.2, dur: 3 },
    { title: 'FREEZE STAKING', msg: 'Fitur staking LilyBit dihentikan sementara karena audit internal.', type: 'bear', ticker: 'LBT', mult: -2.5, dur: 8 },
    { title: 'EXCHANGE LISTING', msg: 'LilyBit kini terdaftar di bursa kripto internasional raksasa!', type: 'bull', ticker: 'LBT', mult: 1.9, dur: 7 },
    { title: 'DEFI INTEGRATION', msg: 'LilyBit kini bisa digunakan sebagai jaminan di platform DeFi.', type: 'bull', ticker: 'LBT', mult: 2.1, dur: 6 },
    { title: 'WHALE DUMP', msg: 'Seorang Whale membuang 1 Juta koin LBT ke pasar sekaligus.', type: 'bear', ticker: 'LBT', mult: -2.6, dur: 3 },
    { title: 'MEME COIN RALLY', msg: 'LBT tiba-tiba menjadi tren meme coin di kalangan Gen-Z.', type: 'bull', ticker: 'LBT', mult: 2.8, dur: 4 },
    { title: 'WALLET HACK', msg: 'Laporan dompet LilyBit versi lama berhasil dibobol peretas.', type: 'bear', ticker: 'LBT', mult: -2.9, dur: 5 },
    { title: 'FIAT PAIRING', msg: 'LilyBit mendapatkan pasangan trading langsung dengan mata uang fiat.', type: 'bull', ticker: 'LBT', mult: 1.8, dur: 8 },
    { title: 'REGULATORY PROBE', msg: 'Otoritas keuangan menyelidiki LilyBit atas dugaan pencucian uang.', type: 'bear', ticker: 'LBT', mult: -2.4, dur: 6 },
    { title: 'STAKING REWARDS UP', msg: 'Bunga staking LBT dinaikkan 20%, menarik banyak holder jangka panjang.', type: 'bull', ticker: 'LBT', mult: 1.9, dur: 7 },
    { title: 'NETWORK CONGESTION', msg: 'Jaringan LilyBit macet parah, biaya transaksi meroket 1000%!', type: 'bear', ticker: 'LBT', mult: -1.8, dur: 4 },
    { title: 'CELEB SHILLING', msg: 'Influencer finansial ternama secara terang-terangan mempromosikan LBT.', type: 'bull', ticker: 'LBT', mult: 2.3, dur: 5 },
    { title: 'DEV WALLET MOVE', msg: 'Dompet kreator LBT yang tertidur 3 tahun tiba-tiba memindahkan saldonya.', type: 'bear', ticker: 'LBT', mult: -2.0, dur: 3 },
    { title: 'FLASH CRASH RUMOR', msg: 'Isu flash crash LBT di sebuah exchange kecil memicu FUD sesaat.', type: 'bear', ticker: 'LBT', mult: -2.2, dur: 4 },
    { title: 'WALLET UI UPDATE', msg: 'Tampilan aplikasi dompet LilyBit diperbarui, user interface lebih mulus!', type: 'bull', ticker: 'LBT', mult: 1.5, dur: 6 },
    { title: 'GAS FEE SPIKE', msg: 'Biaya transaksi gas LBT naik drastis sementara akibat volume padat.', type: 'bear', ticker: 'LBT', mult: -1.6, dur: 5 },
    { title: 'STAKING BONUS', msg: 'Developer memberikan bonus hasil staking acak selama 24 jam ke depan.', type: 'bull', ticker: 'LBT', mult: 1.8, dur: 7 },
    { title: 'PHISHING ATTACK', msg: 'Kampanye email phishing skala besar menargetkan kelalaian pengguna LBT.', type: 'bear', ticker: 'LBT', mult: -1.9, dur: 4 },
    { title: 'DEX LISTING', msg: 'LilyBit akhirnya didukung oleh bursa terdesentralisasi (DEX) populer.', type: 'bull', ticker: 'LBT', mult: 2.0, dur: 6 },
    { title: 'NODE DESYNC', msg: 'Beberapa validator node LBT gagal sinkron, memperlambat jaringan.', type: 'bear', ticker: 'LBT', mult: -1.7, dur: 4 },
    { title: 'CHARITY DONATION', msg: 'Komunitas LBT menyumbang dalam jumlah besar ke badan amal, citra meroket.', type: 'bull', ticker: 'LBT', mult: 1.6, dur: 8 },
    { title: 'FORK RUMOR', msg: 'Isu bahwa komunitas akan membelah (fork) jaringan LBT membuat investor bimbang.', type: 'bear', ticker: 'LBT', mult: -2.1, dur: 5 },
    { title: 'NFT INTEGRATION', msg: 'LBT kini bisa digunakan langsung untuk bertransaksi NFT bertema bunga.', type: 'bull', ticker: 'LBT', mult: 2.1, dur: 7 },
    { title: 'MAINTENANCE DELAY', msg: 'Pemeliharaan rutin server LilyBit memakan waktu jauh lebih lama dari jadwal.', type: 'bear', ticker: 'LBT', mult: -1.8, dur: 4 },
    { title: 'SPONSORSHIP DEAL', msg: 'Logo LilyBit resmi mensponsori turnamen e-sports internasional bergengsi.', type: 'bull', ticker: 'LBT', mult: 1.9, dur: 6 },
    { title: 'FUD CAMPAIGN', msg: 'Kampanye hitam (FUD) tak berdasar oleh kompetitor menyerang citra LilyBit.', type: 'bear', ticker: 'LBT', mult: -1.9, dur: 5 },
    { title: 'MOBILE APP TRENDING', msg: 'Aplikasi LilyBit tiba-tiba masuk jajaran Top 10 di App Store.', type: 'bull', ticker: 'LBT', mult: 2.2, dur: 4 },
    { title: 'API RATE LIMIT', msg: 'Pembatasan API sementara membuat bot trading LBT gagal mengeksekusi order.', type: 'bear', ticker: 'LBT', mult: -1.5, dur: 3 },

    // =========================================================================
    // 👁️ TIER 3: IRISCODE (IRC) - 30 Events
    // =========================================================================
    { title: 'BIO-SCANNER STD', msg: 'IrisCode menjadi standar kode unik untuk bio-scanner militer.', type: 'bull', ticker: 'IRC', mult: 2.0, dur: 5 },
    { title: 'CODE EXPLOIT', msg: 'Celah keamanan fatal ditemukan pada algoritma IrisCode v2.1.', type: 'bear', ticker: 'IRC', mult: -3.0, dur: 6 },
    { title: 'SERGEANT BUY-IN', msg: 'Sekelompok sersan elit melakukan aksi beli besar-besaran IRC!', type: 'bull', ticker: 'IRC', mult: 2.5, dur: 4 },
    { title: 'RIVAL SOFTWARE', msg: 'Muncul pesaing baru "RoseCode" yang mengancam monopoli pasar IRC.', type: 'bear', ticker: 'IRC', mult: -2.2, dur: 5 },
    { title: 'OPEN SOURCE CONTRIB', msg: 'Kontributor global memperbaiki bug utama di sistem IrisCode.', type: 'bull', ticker: 'IRC', mult: 1.8, dur: 10 },
    { title: 'MILITARY CONTRACT', msg: 'Militer memesan jutaan lisensi IrisCode untuk sistem misil otonom.', type: 'bull', ticker: 'IRC', mult: 2.7, dur: 5 },
    { title: 'QUANTUM CRACK', msg: 'Komputer kuantum dikabarkan berhasil memecahkan enkripsi IrisCode.', type: 'bear', ticker: 'IRC', mult: -3.2, dur: 4 },
    { title: 'ENTERPRISE ADOPTION', msg: 'Bank sentral beralih ke IRC untuk mengamankan data nasabah mereka.', type: 'bull', ticker: 'IRC', mult: 2.2, dur: 8 },
    { title: 'LEAD DEV LEFT', msg: 'Pengembang utama IrisCode tiba-tiba mengundurkan diri dan bergabung ke rival.', type: 'bear', ticker: 'IRC', mult: -2.8, dur: 5 },
    { title: 'ZERO-KNOWLEDGE', msg: 'Pembaruan IRC kini mendukung transaksi anonim penuh (ZKP).', type: 'bull', ticker: 'IRC', mult: 2.5, dur: 6 },
    { title: 'ORACLE FAILURE', msg: 'Sistem oracle yang menyuplai harga ke IRC memberikan informasi salah.', type: 'bear', ticker: 'IRC', mult: -2.5, dur: 4 },
    { title: 'INSTITUTIONAL BUY', msg: 'Hedge fund raksasa mengumumkan pembelian masif terhadap IrisCode.', type: 'bull', ticker: 'IRC', mult: 2.4, dur: 7 },
    { title: 'PATENT INFRINGEMENT', msg: 'Gugatan pelanggaran hak cipta internasional mengancam operasi IRC.', type: 'bear', ticker: 'IRC', mult: -2.7, dur: 6 },
    { title: 'V3 MAINNET LAUNCH', msg: 'Peluncuran mainnet IRC versi 3 berjalan sukses luar biasa tanpa celah!', type: 'bull', ticker: 'IRC', mult: 2.6, dur: 5 },
    { title: 'FLASH LOAN ATTACK', msg: 'Eksploitasi pinjaman kilat (Flash Loan) menguras likuiditas IrisCode.', type: 'bear', ticker: 'IRC', mult: -3.0, dur: 3 },
    { title: 'COMPILER BUG', msg: 'Bug minor di kompiler kode sementara waktu membuat developer IRC frustrasi.', type: 'bear', ticker: 'IRC', mult: -1.7, dur: 4 },
    { title: 'HACKATHON WINNER', msg: 'Tim yang memanfaatkan core IrisCode menjuarai ajang Hackathon global.', type: 'bull', ticker: 'IRC', mult: 1.9, dur: 6 },
    { title: 'FALSE POSITIVE BAN', msg: 'Sistem anti-spam IRC keliru memblokir akses pengguna sah sementara waktu.', type: 'bear', ticker: 'IRC', mult: -1.8, dur: 5 },
    { title: 'NEW ALGORITHM', msg: 'Algoritma kompresi data terbaru membuat IrisCode 15% jauh lebih ringan.', type: 'bull', ticker: 'IRC', mult: 2.1, dur: 7 },
    { title: 'EXPIRED CERTIFICATE', msg: 'Sertifikat SSL domain IRC kadaluarsa selama 2 jam, memicu pop-up tidak aman.', type: 'bear', ticker: 'IRC', mult: -2.0, dur: 3 },
    { title: 'PENTAGON AUDIT', msg: 'Pihak militer AS dilaporkan sedang meninjau kelayakan keamanan IrisCode.', type: 'bull', ticker: 'IRC', mult: 2.6, dur: 5 },
    { title: 'LEAKED SOURCE RUMOR', msg: 'Beredar rumor di darkweb bahwa source-code privat IRC telah diretas.', type: 'bear', ticker: 'IRC', mult: -2.4, dur: 4 },
    { title: 'TECH MAGAZINE', msg: 'Sistem canggih IrisCode berhasil masuk ke halaman depan majalah Wired.', type: 'bull', ticker: 'IRC', mult: 1.8, dur: 8 },
    { title: 'SERVER DDOS', msg: 'Serangan botnet DDOS kelas menengah sedikit memperlambat verifikasi biometrik IRC.', type: 'bear', ticker: 'IRC', mult: -1.9, dur: 4 },
    { title: 'BUG BOUNTY PROGRAM', msg: 'IRC meluncurkan kampanye perburuan bug berhadiah jutaan dolar, keamanan terjamin.', type: 'bull', ticker: 'IRC', mult: 2.0, dur: 7 },
    { title: 'DEPENDENCY ISSUE', msg: 'Paket modul eksternal yang digunakan IrisCode mengalami masalah dependensi sesaat.', type: 'bear', ticker: 'IRC', mult: -1.6, dur: 5 },
    { title: 'UNIVERSITY COLLAB', msg: 'IRC kini diakui dan dimasukkan ke dalam kurikulum universitas IT top dunia.', type: 'bull', ticker: 'IRC', mult: 1.7, dur: 9 },
    { title: 'SLOW SYNC', msg: 'Proses sinkronisasi database server IrisCode mengalami kelambatan di region Asia.', type: 'bear', ticker: 'IRC', mult: -1.8, dur: 6 },
    { title: 'BIOMETRIC PATENT', msg: 'IrisCode sah memenangkan hak paten untuk sistem pemindaian retina ultra-cepat.', type: 'bull', ticker: 'IRC', mult: 2.3, dur: 6 },
    { title: 'FORUM BACKLASH', msg: 'Perubahan kebijakan privasi API IRC diprotes keras di forum developer Reddit.', type: 'bear', ticker: 'IRC', mult: -2.1, dur: 5 },

    // =========================================================================
    // 🌐 TIER 4: LOTUSNET (LTN) - 30 Events
    // =========================================================================
    { title: 'UNDERSEA ROOTS', msg: 'Pembangunan kabel bawah laut untuk LotusNet selesai lebih cepat!', type: 'bull', ticker: 'LTN', mult: 2.1, dur: 6 },
    { title: 'DATA BLACKOUT', msg: 'Pemadaman internet regional mengganggu sinkronisasi kluster LotusNet.', type: 'bear', ticker: 'LTN', mult: -2.8, dur: 4 },
    { title: 'CLOUD SUMMIT', msg: 'LotusNet terpilih menjadi tuan rumah untuk Global Cloud Summit.', type: 'bull', ticker: 'LTN', mult: 2.3, dur: 5 },
    { title: 'VAULT LEAK', msg: 'Kebocoran data tingkat tinggi terdeteksi pada brankas Lotus Vault!', type: 'bear', ticker: 'LTN', mult: -3.5, dur: 3 },
    { title: 'CORP MIGRATION', msg: 'Perusahaan teknologi raksasa mulai memigrasikan data ke LotusNodes.', type: 'bull', ticker: 'LTN', mult: 2.0, dur: 8 },
    { title: 'SPACE NODE LAUNCH', msg: 'Satelit pertama yang menjalankan node LotusNet berhasil mengorbit bumi.', type: 'bull', ticker: 'LTN', mult: 2.9, dur: 6 },
    { title: 'FIBER OPTIC CUT', msg: 'Kabel serat optik bawah samudra terputus, mengisolasi jaringan LTN.', type: 'bear', ticker: 'LTN', mult: -3.1, dur: 4 },
    { title: 'METAVERSE HOST', msg: 'LotusNet terpilih sebagai tulang punggung infrastruktur Metaverse terbesar.', type: 'bull', ticker: 'LTN', mult: 2.5, dur: 8 },
    { title: 'SYBIL ATTACK', msg: 'Serangan Sybil skala besar mencoba mengambil alih 51% jaringan LotusNet.', type: 'bear', ticker: 'LTN', mult: -3.4, dur: 3 },
    { title: 'CROSS-CHAIN BRIDGE', msg: 'Jembatan antar-jaringan membuat LTN bisa dipindahkan ke ekosistem lain.', type: 'bull', ticker: 'LTN', mult: 2.2, dur: 7 },
    { title: 'AWS OUTAGE', msg: 'Penyedia cloud terbesar down, mematikan 30% node LotusNet secara paksa.', type: 'bear', ticker: 'LTN', mult: -2.6, dur: 5 },
    { title: 'GAMING PARTNERSHIP', msg: 'Developer game AAA mengadopsi LTN untuk mencetak aset in-game mereka.', type: 'bull', ticker: 'LTN', mult: 2.8, dur: 5 },
    { title: 'GOVERNANCE DRAMA', msg: 'Voting proposal tata kelola LotusNet berujung perpecahan komunitas yang fatal.', type: 'bear', ticker: 'LTN', mult: -2.2, dur: 6 },
    { title: 'TRANSACTION ATH', msg: 'Volume transaksi harian LotusNet mencetak rekor tertinggi sepanjang sejarah!', type: 'bull', ticker: 'LTN', mult: 2.4, dur: 9 },
    { title: 'VALIDATOR SLASHING', msg: 'Validator LTN utama terkena penalti masif karena memanipulasi blok transaksi.', type: 'bear', ticker: 'LTN', mult: -2.7, dur: 4 },
    { title: 'ROUTER CONFIG ERROR', msg: 'Kesalahan konfigurasi software membuat 5% node desentralisasi LTN offline sesaat.', type: 'bear', ticker: 'LTN', mult: -1.7, dur: 5 },
    { title: 'NEW DATA CENTER', msg: 'LotusNet meresmikan pusat data raksasa baru yang 100% bertenaga surya.', type: 'bull', ticker: 'LTN', mult: 2.0, dur: 7 },
    { title: 'COOLING SYSTEM FAIL', msg: 'Sistem pendingin di server Eropa bermasalah, performa jaringan terpaksa diturunkan.', type: 'bear', ticker: 'LTN', mult: -1.9, dur: 4 },
    { title: 'BANDWIDTH UPGRADE', msg: 'Peningkatan bandwidth jaringan LTN besar-besaran sukses dirampungkan tanpa lag.', type: 'bull', ticker: 'LTN', mult: 2.1, dur: 6 },
    { title: 'DNS HIJACK ATTEMPT', msg: 'Upaya pembajakan DNS LotusNet digagalkan, namun rumornya terlanjur memicu FUD.', type: 'bear', ticker: 'LTN', mult: -2.3, dur: 3 },
    { title: 'STREAMING DEAL', msg: 'Layanan streaming film top Hollywood mulai menggunakan LTN untuk distribusi file CDN.', type: 'bull', ticker: 'LTN', mult: 2.4, dur: 8 },
    { title: 'HARDWARE SHORTAGE', msg: 'Kekurangan pasokan server dunia menunda rencana ekspansi node LotusNet bulan ini.', type: 'bear', ticker: 'LTN', mult: -1.8, dur: 6 },
    { title: 'QUANTUM ENCRYPTION', msg: 'Uji coba sistem keamanan enkripsi tahan-kuantum berjalan lancar di testnet LotusNet.', type: 'bull', ticker: 'LTN', mult: 2.5, dur: 7 },
    { title: 'ROUTING LOOP', msg: 'Bug routing BGP menyebabkan sebagian trafik LTN memutar tanpa henti sementara waktu.', type: 'bear', ticker: 'LTN', mult: -2.1, dur: 4 },
    { title: 'GOVERNMENT CONTRACT', msg: 'Pemerintah daerah resmi menggunakan sistem database terdistribusi milik LotusNet.', type: 'bull', ticker: 'LTN', mult: 2.3, dur: 6 },
    { title: 'LATENCY SPIKE', msg: 'Lonjakan ping latensi tiba-tiba di wilayah Amerika Utara mengganggu operasional LTN.', type: 'bear', ticker: 'LTN', mult: -1.6, dur: 5 },
    { title: 'GREEN NODE REWARD', msg: 'Validator LTN yang terbukti menggunakan energi terbarukan diberikan insentif bonus.', type: 'bull', ticker: 'LTN', mult: 1.8, dur: 8 },
    { title: 'UNDERSEA CABLE SHARK', msg: 'Ikan hiu dilaporkan kembali menggigit kabel internet LTN bawah laut, butuh perbaikan.', type: 'bear', ticker: 'LTN', mult: -2.0, dur: 5 },
    { title: 'METAVERSE CONCERT', msg: 'Konser virtual raksasa di Metaverse sukses di-host 100% tanpa lag oleh server LTN.', type: 'bull', ticker: 'LTN', mult: 2.6, dur: 5 },
    { title: 'API OUTAGE', msg: 'Layanan API pemantau pihak ketiga untuk jaringan LotusNet tumbang selama beberapa jam.', type: 'bear', ticker: 'LTN', mult: -1.5, dur: 4 },

    // =========================================================================
    // 🌹 TIER 5: ROSEX (RSX) - 30 Events
    // =========================================================================
    { title: 'AI PERFUME', msg: 'RoseX dipilih secara eksklusif sebagai bahan utama parfum berbasis AI.', type: 'bull', ticker: 'RSX', mult: 2.6, dur: 5 },
    { title: 'CYBER DROUGHT', msg: 'Kekeringan server mematikan separuh dari total suplai bunga RoseX.', type: 'bear', ticker: 'RSX', mult: -3.2, dur: 4 },
    { title: 'CELEBRITY ENDORSE', msg: 'Artis papan atas memamerkan perhiasan berlapis RoseX di karpet merah!', type: 'bull', ticker: 'RSX', mult: 3.0, dur: 3 },
    { title: 'TAX CRACKDOWN', msg: 'Pemerintah mengenakan pajak kemewahan tambahan untuk aset kelas Colonel.', type: 'bear', ticker: 'RSX', mult: -2.5, dur: 7 },
    { title: 'SUPPLY HALVING', msg: 'Produksi algoritma RoseX dikurangi setengahnya untuk memicu kelangkaan.', type: 'bull', ticker: 'RSX', mult: 2.8, dur: 9 },
    { title: 'ROYAL WEDDING', msg: 'Bunga RoseX dijadikan dekorasi utama di pernikahan kerajaan virtual!', type: 'bull', ticker: 'RSX', mult: 3.4, dur: 5 },
    { title: 'SYNTHETIC CLONE', msg: 'Pabrikan gelap memproduksi RoseX sintetis yang membanjiri pasar.', type: 'bear', ticker: 'RSX', mult: -3.5, dur: 6 },
    { title: 'MEDICAL BREAKTHROUGH', msg: 'Ekstrak kode RoseX terbukti mampu memperlambat penuaan sel digital.', type: 'bull', ticker: 'RSX', mult: 3.2, dur: 7 },
    { title: 'BOYCOTT CAMPAIGN', msg: 'Aktivis lingkungan memboikot RoseX karena limbah energinya.', type: 'bear', ticker: 'RSX', mult: -2.9, dur: 5 },
    { title: 'VIRTUAL IDOL', msg: 'Idol virtual terpopuler merilis lagu berjudul "RoseX" dan meledak di tangga lagu.', type: 'bull', ticker: 'RSX', mult: 3.0, dur: 4 },
    { title: 'DELISTING RUMOR', msg: 'Bursa utama di Asia mengancam akan menghapus RoseX dari daftarnya.', type: 'bear', ticker: 'RSX', mult: -3.3, dur: 3 },
    { title: 'LUXURY COLLAB', msg: 'Brand fashion ternama Paris merilis tas edisi terbatas dengan chip RoseX.', type: 'bull', ticker: 'RSX', mult: 2.9, dur: 6 },
    { title: 'TOXIC MUTATION', msg: 'Bug mutasi genetik membuat varian RoseX baru mengeluarkan data yang korup.', type: 'bear', ticker: 'RSX', mult: -3.1, dur: 4 },
    { title: 'BULLISH DIVERGENCE', msg: 'Indikator teknikal RoseX menunjukkan sinyal beli yang sangat tidak wajar.', type: 'bull', ticker: 'RSX', mult: 2.7, dur: 8 },
    { title: 'TAX SEIZURE', msg: 'Pemerintah menyita dompet pemegang RoseX terbesar karena penggelapan pajak.', type: 'bear', ticker: 'RSX', mult: -3.6, dur: 3 },
    { title: 'DESIGN LEAK', msg: 'Desain kemasan estetika RoseX musim depan bocor secara prematur ke publik.', type: 'bear', ticker: 'RSX', mult: -1.8, dur: 5 },
    { title: 'PARIS FASHION WEEK', msg: 'Estetika RoseX sukses mendominasi panggung utama di ajang Paris Fashion Week!', type: 'bull', ticker: 'RSX', mult: 2.5, dur: 6 },
    { title: 'INFLUENCER SCANDAL', msg: 'Brand ambassador utama RoseX tersandung skandal kecil, membuat citra koin menurun.', type: 'bear', ticker: 'RSX', mult: -2.4, dur: 4 },
    { title: 'NEW PERFUME LINE', msg: 'RoseX merilis varian feromon digital baru yang sangat diminati kolektor elit.', type: 'bull', ticker: 'RSX', mult: 2.3, dur: 7 },
    { title: 'FACTORY PROTEST', msg: 'Buruh data di pabrik render RoseX melakukan aksi mogok kerja menuntut upah.', type: 'bear', ticker: 'RSX', mult: -2.1, dur: 6 },
    { title: 'ROYALTY ENDORSEMENT', msg: 'Anggota keluarga bangsawan Eropa tertangkap kamera menggunakan NFT aksesori RoseX.', type: 'bull', ticker: 'RSX', mult: 2.7, dur: 5 },
    { title: 'COUNTERFEIT SCARE', msg: 'Polisi siber menggerebek pabrik RoseX tiruan, membuat pembeli ritel jadi ragu berbelanja.', type: 'bear', ticker: 'RSX', mult: -2.6, dur: 5 },
    { title: 'GENETIC PATENT', msg: 'Hak paten legal untuk mutasi warna mawar emas digital berhasil diamankan RSX.', type: 'bull', ticker: 'RSX', mult: 2.4, dur: 8 },
    { title: 'MATERIAL DELAY', msg: 'Pengiriman bahan baku polimer untuk kotak kolektor RoseX terlambat, peluncuran ditunda.', type: 'bear', ticker: 'RSX', mult: -1.9, dur: 7 },
    { title: 'K-POP COLLAB', msg: 'Grup K-Pop paling terkenal di dunia merilis merchandise eksklusif edisi terbatas RoseX.', type: 'bull', ticker: 'RSX', mult: 3.1, dur: 4 },
    { title: 'ALLERGIC RUMOR', msg: 'Rumor palsu tentang radiasi ringan pada material render RoseX menyebar di grup gosip.', type: 'bear', ticker: 'RSX', mult: -2.3, dur: 4 },
    { title: 'MAGAZINE AWARDS', msg: 'RoseX secara aklamasi dinobatkan sebagai "Digital Luxury Asset of the Year" oleh majalah Vogue.', type: 'bull', ticker: 'RSX', mult: 2.2, dur: 6 },
    { title: 'ECO-CRITICISM', msg: 'Jurnalis lingkungan mempublikasikan artikel yang mengkritik tingginya karbon footprint RoseX.', type: 'bear', ticker: 'RSX', mult: -2.2, dur: 5 },
    { title: 'VIRTUAL RUNWAY', msg: 'Acara fashion show virtual di Metaverse berjalan luar biasa sukses berkat atribut grafis RSX.', type: 'bull', ticker: 'RSX', mult: 2.4, dur: 5 },
    { title: 'PRICE GOUGING', msg: 'Konsumen ritel merencanakan boikot sementara karena harga RoseX dianggap terlalu mencekik.', type: 'bear', ticker: 'RSX', mult: -2.5, dur: 4 },

    // =========================================================================
    // 🌷 TIER 6: TULIPNEX (TNX) - 30 Events
    // =========================================================================
    { title: 'ACQUISITION', msg: 'TulipNex Inc. resmi mengakuisisi 3 perusahaan kompetitor teknologi utama!', type: 'bull', ticker: 'TNX', mult: 3.5, dur: 5 },
    { title: 'CEO RESIGN', msg: 'CEO TulipNex mendadak mengundurkan diri tanpa alasan, pasar panik luar biasa!', type: 'bear', ticker: 'TNX', mult: -4.0, dur: 4 },
    { title: 'NEXUS CORE UPGRADE', msg: 'Pembaruan Nexus Core membuat ekosistem TNX tidak mungkin diretas.', type: 'bull', ticker: 'TNX', mult: 2.9, dur: 8 },
    { title: 'FALSE RUMOR', msg: 'Rumor palsu tentang kebangkrutan TNX tersebar luas di seluruh media!', type: 'bear', ticker: 'TNX', mult: -3.0, dur: 2 },
    { title: 'GALACTIC RESERVE', msg: 'Federasi Botani Galaksi meresmikan TNX sebagai mata uang cadangan.', type: 'bull', ticker: 'TNX', mult: 4.5, dur: 6 },
    { title: 'MARS COLONY ADOPTION', msg: 'Koloni manusia pertama di Mars menggunakan TNX sebagai alat tukar.', type: 'bull', ticker: 'TNX', mult: 4.8, dur: 6 },
    { title: 'QUANTUM CRASH', msg: 'Kecerdasan Buatan (AI) terkuat memprediksi TNX akan hancur besok.', type: 'bear', ticker: 'TNX', mult: -4.5, dur: 4 },
    { title: 'SUPER BOWL ADS', msg: 'Iklan TulipNex tayang di Super Bowl, disaksikan ratusan juta penonton.', type: 'bull', ticker: 'TNX', mult: 3.8, dur: 5 },
    { title: 'GLOBAL BAN', msg: 'Tiga negara adidaya bersatu untuk memblokir seluruh transaksi TNX.', type: 'bear', ticker: 'TNX', mult: -5.0, dur: 3 },
    { title: 'TIME TRAVELER TWEET', msg: 'Sebuah akun dari tahun 2050 men-tweet "Beli TNX sekarang juga!".', type: 'bull', ticker: 'TNX', mult: 4.2, dur: 4 },
    { title: 'INSIDER EXPOSED', msg: 'Jajaran eksekutif TulipNex tertangkap FBI melakukan insider trading massal.', type: 'bear', ticker: 'TNX', mult: -4.2, dur: 5 },
    { title: 'IMMORTALITY SERUM', msg: 'TNX diklaim sebagai satu-satunya alat pembayaran untuk serum keabadian.', type: 'bull', ticker: 'TNX', mult: 5.0, dur: 7 },
    { title: 'NETWORK HIJACK', msg: 'Grup Hacker menguasai 51% hash rate jaringan TulipNex selama satu jam.', type: 'bear', ticker: 'TNX', mult: -4.8, dur: 3 },
    { title: 'ETF APPROVAL', msg: 'TulipNex ETF disetujui secara legal, triliunan dana institusi masuk seketika!', type: 'bull', ticker: 'TNX', mult: 4.0, dur: 8 },
    { title: 'CREATOR DUMP', msg: 'Dompet kreator anonim yang tidak pernah disentuh kini membuang seluruh TNX-nya.', type: 'bear', ticker: 'TNX', mult: -4.6, dur: 4 },
    { title: 'LEGAL SCRUTINY', msg: 'Beredar isu komisi perdagangan sekuritas sedang menginvestigasi monopoli TulipNex.', type: 'bear', ticker: 'TNX', mult: -2.8, dur: 6 },
    { title: 'DIVIDEND SURPRISE', msg: 'TulipNex mengumumkan pembagian dividen kejutan akhir tahun untuk para holdernya.', type: 'bull', ticker: 'TNX', mult: 3.2, dur: 5 },
    { title: 'Q3 EARNINGS MISS', msg: 'Laporan pendapatan kuartal ketiga TNX ternyata sedikit di bawah ekspektasi pasar global.', type: 'bear', ticker: 'TNX', mult: -2.5, dur: 5 },
    { title: 'MERGER RUMOR', msg: 'Rumor bahwa TulipNex akan melakukan mega-merger dengan raksasa teknologi lain memicu euforia.', type: 'bull', ticker: 'TNX', mult: 3.4, dur: 4 },
    { title: 'EXECUTIVE LEAK', msg: 'Memo internal direksi TNX bocor ke publik, mengindikasikan program pemotongan biaya besar-besaran.', type: 'bear', ticker: 'TNX', mult: -2.6, dur: 5 },
    { title: 'SPACE HOTEL', msg: 'TulipNex meresmikan investasi miliaran dolar untuk proyek hotel luar angkasa komersial pertama.', type: 'bull', ticker: 'TNX', mult: 3.6, dur: 7 },
    { title: 'ANTITRUST LAWSUIT', msg: 'Gugatan antimonopoli diajukan oleh koalisi perusahaan saingan yang mencoba menjatuhkan TNX.', type: 'bear', ticker: 'TNX', mult: -3.0, dur: 6 },
    { title: 'NEW CEO INITIATIVE', msg: 'CEO baru TulipNex naik mimbar dan mengumumkan visi ekspansi ambisius untuk dekade berikutnya.', type: 'bull', ticker: 'TNX', mult: 3.1, dur: 6 },
    { title: 'BOARDROOM DRAMA', msg: 'Isu perselisihan sengit antar anggota dewan direksi TulipNex mencuat di headline media finansial.', type: 'bear', ticker: 'TNX', mult: -2.9, dur: 4 },
    { title: 'NEXUS PHONE', msg: 'Kejutan! TulipNex meluncurkan prototipe smartphone eksklusif yang berjalan di atas node mereka sendiri.', type: 'bull', ticker: 'TNX', mult: 3.5, dur: 5 },
    { title: 'TAX EVASION RUMOR', msg: 'Beredar gosip tak berdasar di forum deep-web mengenai manipulasi laporan pajak TulipNex.', type: 'bear', ticker: 'TNX', mult: -3.2, dur: 3 },
    { title: 'STADIUM SPONSOR', msg: 'Konsorsium TNX secara resmi membeli hak nama stadion olahraga terbesar di benua Amerika.', type: 'bull', ticker: 'TNX', mult: 2.8, dur: 8 },
    { title: 'ALGORITHM GLITCH', msg: 'Algoritma High-Frequency Trading (HFT) milik TNX mengalami glitch kecil, menyebabkan erosi harga sesaat.', type: 'bear', ticker: 'TNX', mult: -2.4, dur: 4 },
    { title: 'INDEX INCLUSION', msg: 'Saham TulipNex secara resmi dimasukkan ke dalam indeks elit global setara S&P 500!', type: 'bull', ticker: 'TNX', mult: 3.8, dur: 9 },
    { title: 'PR DISASTER', msg: 'Cuitan kontroversial dari salah satu petinggi TulipNex memicu kemarahan cancel culture netizen sesaat.', type: 'bear', ticker: 'TNX', mult: -2.7, dur: 3 }
];

/**
 * Ekspor array event agar bisa di-require oleh file lain
 */
module.exports = eventPool;